APP_NAME = '邮件收发工具'
APP_VERSION = '1.0.0'

DEFAULT_SMTP_PORT = 587
DEFAULT_SMTP_SERVER = 'smtp.qq.com'

EMAIL_SUBJECT_DEFAULT = '邮件收发工具'
EMAIL_SUBJECT_BATCH = '批量邮件发送'

STATUS_NOT_SENT = '未发送'
STATUS_SENT = '已发送'
STATUS_CANCELED = '已取消'

CONTENT_NONE = '无内容'
CONTENT_HAVING = '有内容'

BATCH_TABLE_HEADERS = ['收件人姓名', '收件人邮箱', '邮件标题', '内容/文件', '状态']

TABLE_COLUMN_RECIPIENT_NAME = 0
TABLE_COLUMN_RECIPIENT_EMAIL = 1
TABLE_COLUMN_SUBJECT = 2
TABLE_COLUMN_CONTENT = 3
TABLE_COLUMN_STATUS = 4

PROGRESS_DIALOG_TITLE = '正在处理...'
PROGRESS_DIALOG_CANCEL = '取消'
RESULT_DIALOG_SUCCESS = '成功'
RESULT_DIALOG_FAILED = '失败'
RESULT_DIALOG_CANCELED = '已取消'

MSG_WARN_NO_RECIPIENT = '请填写收件人邮箱'
MSG_WARN_INVALID_EMAIL = '收件人邮箱格式不正确'
MSG_WARN_NO_EMAIL_LIST = '请添加要发送的邮件列表'
MSG_WARN_EMPTY_BATCH = '批量列表为空，请先添加数据'
MSG_SUCCESS_IMPORT = 'CSV文件导入成功！'
MSG_SUCCESS_RESET = '表单已重置'
MSG_SUCCESS_APPLY_ALL = '已将当前内容应用于所有行'
MSG_SUCCESS_SEND = '邮件发送成功！'
MSG_FAILED_SEND = '邮件发送失败'
MSG_ERROR_IMPORT = '导入失败'